/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AssetryEscrowInterface extends Interface {
    getFunction(nameOrSignature: "confirmDelivery" | "deposit" | "escrows" | "getEscrow" | "refund"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Confirmed" | "Deposited" | "Refunded"): EventFragment;

    encodeFunctionData(functionFragment: 'confirmDelivery', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'escrows', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getEscrow', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'refund', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'confirmDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
  }

  
    export namespace ConfirmedEvent {
      export type InputTuple = [purchaseId: BytesLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [purchaseId: string, seller: string, amount: bigint];
      export interface OutputObject {purchaseId: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [purchaseId: BytesLike, buyer: AddressLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [purchaseId: string, buyer: string, seller: string, amount: bigint];
      export interface OutputObject {purchaseId: string, buyer: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [purchaseId: BytesLike, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [purchaseId: string, buyer: string, amount: bigint];
      export interface OutputObject {purchaseId: string, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AssetryEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): AssetryEscrow;
    waitForDeployment(): Promise<this>;

    interface: AssetryEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    confirmDelivery: TypedContractMethod<
      [purchaseId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [purchaseId: BytesLike, seller: AddressLike, ],
      [void],
      'payable'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }],
      'view'
    >
    

    
    getEscrow: TypedContractMethod<
      [purchaseId: BytesLike, ],
      [[string, string, bigint, bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [purchaseId: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'confirmDelivery'): TypedContractMethod<
      [purchaseId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [purchaseId: BytesLike, seller: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrow'): TypedContractMethod<
      [purchaseId: BytesLike, ],
      [[string, string, bigint, bigint] & {buyer: string, seller: string, amount: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [purchaseId: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Confirmed'): TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;

    filters: {
      
      'Confirmed(bytes32,address,uint256)': TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
      Confirmed: TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
    

      'Deposited(bytes32,address,address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'Refunded(bytes32,address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    
    };
  }